Additional style class selectors
SteveBrandt/gulp-css-scala pull request #5
Opened 2017-04-03 11:40 UTC by SteveBrandt

2017-04-03 17:48 UTC, marttinen requested changes

2017-04-03 17:48 UTC, marttinen commented on index.js
> +var selectors = [];
State!

2017-04-03 18:02 UTC, marttinen commented on index.js
> +var selectors = [];
I don't get the reason behind `selectors` and `resetSelectors`...

2017-04-03 18:33 UTC, marttinen commented on index.js
> +var selectors = [];
Ok, I get it now. Its for supporting multiple files. But its still not a pretty solution... 🤔

2017-04-04 05:09 UTC, SteveBrandt commented on index.js
> +var selectors = [];
I'll think about it

2017-04-04 19:27 UTC, merged